version: '2'

services:

  crudular-angular:
    build:
      context: .
      dockerfile: ./.docker/crudular-angular.development.dockerfile
    command: ng serve --host 0.0.0.0 --port 4200
    container_name: crudular-angular-serve-dev
    image: crudular-angular
    networks:
      - dev-network
    ports:
      - '4200:4200'

networks:
  dev-network:
    driver: bridge
